version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089" # Mapea el puerto del contenedor al puerto local
    environment:
      - MONGOURI=mongodb+srv://migueljaraespinoza97:E6RJiqqqUYOZtyQT@cluster0.4ux3s.mongodb.net/E-commerce2
      - PORT=8089
      - COOKIE_SECRET=B64v8C&^1j4ME6XOcx3w&g+-jY[jbyprq$
      - pkey=pk_test_51R4AqFHUIGEjsx9yBRukJm3J0A70NM14TS7NU4UOBLsQi2yQObr7Fj36u4LUXztJHjs2QvvHat9T6sAYi6CK29yS00wyx5fRoN
      - skey=sk_test_51R4AqFHUIGEjsx9yqqwkxQsj0AqysX15Sw1ZpVHjxW6VGdBwuD9V2StkrpiWhbFwKtzwnGu6r8RRpUl2GiLVP8hH009P5tm33O
      - jwtSecret=9!P4t93$}c%N8.pL)m7_>0nWZ+_3xU03TnF/Va1$c>l^|i*~"z
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: